### ISSUE TITLE
Todo before going to production

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/c2c_ui#63]
Here is a task list to do before going to production : 

* [x] rebuild site maps 
* [x] Advertising banner
* [x] yeti
* [x] remove isUserSafe property from BaseApi (usefull during project period, but not after)
* [x] google analytics
* [x] configure production server
* [x] create robots.txt only for prod builds
*  ...

**Comment by brunobesson** [comment]
The UI will have to run on a production-ready server, too.

**Comment by cbeauchesne** [comment]
@brunobesson, can we check the tick "configure production server" ?

**Comment by brunobesson** [comment]
I think so, yes. You can update and test the demo.

**Comment by cbeauchesne** [comment]
*brunobesson closed this 2 days ago*

Yeah !!!! 😎
